export const ORG_DOC_CREATE_ERROR = "ORG_DOC_CREATE_ERROR";

export const ORG_DOC_NOT_FOUND_ERROR = "ORG_DOC_NOT_FOUND_ERROR";

export const FILE_TYPE_VALIDATION_ERROR = "FILE_TYPE_VALIDATION_ERROR";

export const PARTNER_PERMISSIONS_AGREEMENT_DATA_UPDATE_FAILED =
  "PARTNER_PERMISSIONS_AGREEMENT_DATA_UPDATE_FAILED";
export const EMAIL_NOTIFICATION_ERROR = "EMAIL_NOTIFICATION_ERROR";
