export const AUTH_ALREADY_VERIFIED_ERROR = 'AUTH_ALREADY_VERIFIED_ERROR';
export const AUTH_CREATE_ERROR = 'AUTH_CREATE_ERROR';
export const AUTH_EXPIRED_SESSION_ERROR = 'AUTH_EXPIRED_SESSION_ERROR';
export const AUTH_INVALID_TOKEN_ERROR = 'AUTH_INVALID_TOKEN_ERROR';
export const AUTH_NOT_FOUND_ERROR = 'AUTH_NOT_FOUND_ERROR';
export const AUTH_TOO_MANY_REQUEST_ERROR = 'AUTH_TOO_MANY_REQUEST_ERROR';
